### ISSUE TITLE
Meld still running in background after merge.

### ISSUE THREAD

**Issue by mitu-lv** [yousseb/meld#74] opened 2018-12-07 10:40 UTC
After merging files on `MacOs Mojave` using `git mergetool` with 3.19.2(r2) meld is still running in background with two processes `Meld-bin` and `Meld (Not Responding)`

**Comment by yousseb** [comment] 2018-12-16 07:30
Please check on this build
https://github.com/yousseb/meld/releases/tag/osx-13

**Comment by yousseb** [comment] 2018-12-17 15:15
Duplicate of #75

**Closed by yousseb** 2018-12-17 15:15 UTC
